### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by PythonMasterAlexander** [PythonMasterAlexander/alexander-hardeland-semester-project-2#13]
Writte a error message as a own function and put it in the utilities directory
- The error message must display to the user if the API call is not working
- The message must be outputed on the page for the user to see
- The message can be reusable as a function in it's own file

**Comment by cnnrbrn** [comment]
The errorMessage function depends on an element with class of product-container existing, so might not be reusable across pages.

Consider adding a default value to the function parameter:

`(errorMessage = "An error occurred")`

**Comment by PythonMasterAlexander** [comment]
Updated the code with two new functions and a new file with one of the functions where I add sass warning classes and attribute to the container element.

The error function now has a default function parameter
The error function can now be used without the specified class of product-container
